"""Emit a Timemachine ("tmd") force field by merging freshly fit bespoke torsions onto
an existing tmd force field.

tmd serialises a force field as a Python ``dict`` literal (loaded via
``ast.literal_eval``) in OpenMM MD units (kJ/mol, nm, radians). This module merges
bespoke ``ProperTorsion`` parameters into a base tmd force field, leaving every other
handler -- bonds, angles, impropers, vdW and, crucially, the charge handler -- identical
to the base. That keeps the base force field's charges and remaining parameters intact
for FEP while avoiding the lossy round-trips of a full OpenFF<->tmd conversion.

The proper-torsion unit handling mirrors tmd's own SMIRNOFF converter
(``tmd/ff/smirnoff_converter.py``): each per-term force constant is divided by ``idivf``
and stored in kJ/mol, the phase in radians, and the periodicity as a float.

The functions here only depend on the standard library; the OpenFF helpers
(:func:`collect_fitted_torsions`) operate on already-constructed ``ForceField`` objects
that the caller supplies, so this module can be imported without the OpenFF toolkit.
"""

import ast
import copy
import pprint
from typing import List, Tuple

# Top-level dict key tmd uses for the proper-torsion handler.
_PROPER_TORSION_KEY = "ProperTorsion"

# Number of force-constant terms an OpenFF proper torsion may define (k1..k6).
_MAX_TORSION_TERMS = 6


def load_tmd_force_field(path: str) -> dict:
    """Load a tmd-format force field (a Python ``dict`` literal) from ``path``."""
    with open(path) as file:
        force_field = ast.literal_eval(file.read())

    if not isinstance(force_field, dict):
        raise ValueError(
            f"{path} does not contain a tmd force field dictionary literal."
        )

    return force_field


def save_tmd_force_field(force_field: dict, path: str) -> None:
    """Write a tmd-format force field ``dict`` to ``path`` as a Python ``dict`` literal
    that tmd can load with ``ast.literal_eval`` (a leading comment is permitted, matching
    tmd's own parameter files)."""
    with open(path, "w") as file:
        file.write("# Generated by openff-bespoke; tmd force field dictionary.\n")
        pprint.PrettyPrinter(width=500, compact=False, stream=file, indent=2).pprint(
            force_field
        )


def tmd_proper_torsion_smirks(force_field: dict) -> set:
    """Return the set of ``ProperTorsion`` SMIRKS present in a tmd force field dict."""
    patterns = force_field.get(_PROPER_TORSION_KEY, {}).get("patterns", [])
    return {entry[0] for entry in patterns}


def proper_torsion_to_tmd_pattern(parameter) -> list:
    """Convert an OpenFF ``ProperTorsionType`` to a tmd ``ProperTorsion`` pattern of the
    form ``[smirks, [[k, phase, period], ...]]``.

    Each force constant is divided by ``idivf`` and expressed in kJ/mol, the phase in
    radians and the periodicity as a float, matching tmd's own SMIRNOFF converter.
    """
    components = []

    for i in range(1, _MAX_TORSION_TERMS + 1):
        k = getattr(parameter, f"k{i}", None)
        if k is None:
            break

        idivf = getattr(parameter, f"idivf{i}", None)
        idivf = 1.0 if idivf is None else float(idivf)

        components.append(
            [
                k.m_as("kilojoule / mole") / idivf,
                getattr(parameter, f"phase{i}").m_as("radian"),
                float(getattr(parameter, f"periodicity{i}")),
            ]
        )

    return [parameter.smirks, components]


def merge_torsions_into_tmd(
    base_force_field: dict, parameters: List
) -> Tuple[dict, List[str], List[str]]:
    """Merge OpenFF proper-torsion ``parameters`` into a copy of ``base_force_field``.

    If a parameter's SMIRKS already exists in the base force field its entry is
    **overwritten** with the newly fit parameters; otherwise the parameter is appended.
    In other words a fit torsion always wins over a matching base torsion.

    Returns the merged force field, the SMIRKS that were appended, and the SMIRKS that
    overwrote an existing base torsion.
    """
    force_field = copy.deepcopy(base_force_field)

    handler = force_field.setdefault(_PROPER_TORSION_KEY, {"patterns": []})
    patterns = handler.setdefault("patterns", [])

    index_by_smirks = {entry[0]: i for i, entry in enumerate(patterns)}

    added: List[str] = []
    replaced: List[str] = []

    for parameter in parameters:
        pattern = proper_torsion_to_tmd_pattern(parameter)
        smirks = pattern[0]

        if smirks in index_by_smirks:
            patterns[index_by_smirks[smirks]] = pattern
            replaced.append(smirks)
        else:
            index_by_smirks[smirks] = len(patterns)
            patterns.append(pattern)
            added.append(smirks)

    return force_field, added, replaced


def _proper_torsion_signature(parameter) -> tuple:
    """A hashable, comparable signature of a proper torsion's fitted values, used to tell
    whether a refit torsion differs from its base counterpart."""
    terms = []

    for i in range(1, _MAX_TORSION_TERMS + 1):
        k = getattr(parameter, f"k{i}", None)
        if k is None:
            break

        idivf = getattr(parameter, f"idivf{i}", None)
        idivf = 1.0 if idivf is None else float(idivf)

        terms.append(
            (
                round(k.m_as("kilojoule / mole"), 8),
                round(getattr(parameter, f"phase{i}").m_as("radian"), 8),
                int(getattr(parameter, f"periodicity{i}")),
                round(idivf, 8),
            )
        )

    return tuple(sorted(terms))


def collect_fitted_torsions(refit_force_fields: List, base_force_field) -> list:
    """Return the proper-torsion parameters that the bespoke fits introduced or changed.

    A torsion is considered *fitted* if its SMIRKS is absent from ``base_force_field`` or
    if its values differ from the matching base torsion. Torsions left untouched
    (identical to the base) are ignored so only genuinely fit parameters are emitted.
    Parameters are de-duplicated by SMIRKS across the supplied force fields (first
    occurrence wins).

    Args:
        refit_force_fields: The bespoke (refit) ``ForceField`` objects, one per molecule.
        base_force_field: The OpenFF ``ForceField`` the fits started from.
    """
    base_handler = base_force_field.get_parameter_handler("ProperTorsions")
    base_signatures = {
        parameter.smirks: _proper_torsion_signature(parameter)
        for parameter in base_handler.parameters
    }

    fitted = []
    seen = set()

    for force_field in refit_force_fields:
        handler = force_field.get_parameter_handler("ProperTorsions")

        for parameter in handler.parameters:
            if parameter.smirks in seen:
                continue

            base_signature = base_signatures.get(parameter.smirks)
            if base_signature is not None and base_signature == _proper_torsion_signature(
                parameter
            ):
                # An inherited base torsion the fit left untouched.
                continue

            fitted.append(parameter)
            seen.add(parameter.smirks)

    return fitted
